---
- name: Arduino IDE
  vars:
    arduino_path: "/home/{{ ansible_user }}/Arduino"
    script_path: "/tmp/arduino-udev-setup.sh"

  block:
   
    - name: Install dependency libfuse2t64
      ansible.builtin.apt:
        name: libfuse2t64
        state: present
        update_cache: false
      
    - name: Create Arduino directory in HOME
      ansible.builtin.file:
        path: "{{ arduino_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Download Arduino AppImage
      community.general.appimage:
        name: "Arduino-IDE.AppImage"
        install_dir: "{{ arduino_path }}"
        url: https://downloads.arduino.cc/arduino-ide/arduino-ide_latest_Linux_64bit.AppImage
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: "present"
        
    - name: Add user to dialout group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: dialout
        append: true

    - name: Add user to tty group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: tty
        append: true

    - name: Add user to plugdev group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: plugdev
        append: true

    - name: Check if Arduino udev rule already exists
      ansible.builtin.stat:
        path: /etc/udev/rules.d/60-arduino-combined.rules
      register: arduino_udev_file
        
    - name: Download arduino-udev-setup.sh
      get_url: 
        url: https://content.arduino.cc/assets/arduino-udev-setup.sh
        dest: "{{ script_path }}"
        mode: '0664'
      when: not arduino_udev_file.stat.exists

    - name: Execute udev shell script
      ansible.builtin.shell:
        cmd: "bash {{ script_path }}"
      when: not arduino_udev_file.stat.exists

    - name: Remove script from TMP
      file: 
        path: "{{ script_path }}"
        state: absent
      when: not arduino_udev_file.stat.exists
        
    - name: Final info
      ansible.builtin.debug:
        msg:
        - "Reboot must be done before user can reach USB port."
        - "Because of AppArmor bug AppImage must be run with:"
        - "{{ arduino_path }}/Arduino-IDE.AppImage --no-sandbox"
        
        
        
        